CREATE TABLE anime_watchlists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES anime_users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    image_url TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);
